apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: keycloak
    targetRevision: 9.2.2
    helm:
      parameters:
        - name: auth.adminUser
          value: admin
      values: |
        initContainers:
            - name: theme
              image: openinnovationai/keycloak-theme:1.0.0
              imagePullPolicy: Always
              command:
                - sh
              args:
                - -c
                - |
                  echo "Copying custome login theme"
                  cp -R /themes/default/* /theme
              volumeMounts:
                - name: theme
                  mountPath: /theme
        global:
          imagePullSecrets:
            - dockerconfigjson
        extraVolumes: |
          - name: theme
            mountPath: /theme

        extraVolumeMounts: |
          - name: theme
            mountPath: /opt/bitnami/keycloak/themes/default                          

  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true 
  revisionHistoryLimit: 1

