apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoUrl }}
    path: keycloak
    targetRevision: {{ .Values.targetRevision }}
    helm:
      values: |
        keycloak:
        {{- toYaml .Values.prometheus | nindent 10 }}
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
  revisionHistoryLimit: 1