apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: keycloak
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ {{ .Values.spec.source.repoURL }} }}
    path: keycloak
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        keycloak:
        {{- toYaml .Values.prometheus | nindent 10 }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: keycloak
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
  revisionHistoryLimit: 1