apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: redis
    targetRevision: 18.1.0
  destination:
    namespace: redis
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - PruneLast=true
    - CreateNamespace=true
  revisionHistoryLimit: 1